### ISSUE TITLE
Repo privado

### ISSUE THREAD

**Issue by EmilioSalgado** [UG-Mobile2016/Pr-ctica-1#1]
Profe es forzoso agregar una tarjeta de crédito para hacer uso del repositorio privado

Hice uso del GitHub Student Pack para el uso gratuito, pero según me responderán en unas semanas.

Hay otras alternativas?

**Comment by diegosaul402** [comment]
A mi también me dijeron que me respondían en unas semanas, pero el correo de acepación me llegó a los 15 segundos, y no necesité tarjeta

**Comment by EmilioSalgado** [comment]
si tienes razón ya me llego también

**Comment by JuanCrg90** [comment]
sorry apenas vi esto, y no no se ocupa tarjeta. Que bueno que ya pudieron. Cierro el hilo.
