### ISSUE TITLE
Problema al agregar los valores

### ISSUE THREAD

**Issue by Oswaldofm17** [UG-Mobile2016/Pr-ctica-1#2]
Mi problema principal es que no puedo agregar los valores que voy obteniendo a la lista y por consecuente no puedo pasar a lo siguiente, ya revisé todos los archivos e incluso pedí ayuda a algunos de mis compañeros pero seguimos sin encontrar el problema aparente.

Hice revisión del adapter y los archivos xml, pero nada me resuelve el problema.

**Comment by JuanCrg90** [comment]
¿Ya probaste hacer `Log.v` de lo que envias a traves del fragment listener?

**Comment by Oswaldofm17** [comment]
Ya lo probé en otro celular y corrió bien, entonces es el celular el que me está dando el problema, a que se podría deber?

**Comment by Oswaldofm17** [comment]
Problema resuelto, no supimos a que se debía, empezó a funcionar luego de probarlo en otro dispositivo
